services:
  - type: web
    name: novofitbd # You can name this whatever you like
    env: static
    staticPublishPath: . # Serve files from the root directory
    rewrites:
      - source: "/:path*"
        destination: "/:path*.html"
